### ISSUE TITLE
使用报错记录，请问大佬，这个怎么解决呀？

### ISSUE THREAD

**Issue by wb3368316006** [ashinnotfound/ChatGPT-QQRobot#10]
<img width="1621" alt="问题" src="https://user-images.githubusercontent.com/89630969/218421199-75471249-476e-458e-9b22-918420595ac6.png">

**Comment by ashinnotfound** [comment]
大概是提问历史记录太长，被拒绝请求了，我待会处理一下这个。目前一个暂行的方法是向机器人发送“重置会话”四个字。

**Comment by ashinnotfound** [comment]
这个问题解决了（应该是的🤪）
