### ISSUE TITLE
更新之后又来了 503 错误

### ISSUE THREAD

**Issue by wb3368316006** [ashinnotfound/ChatGPT-QQRobot#11]
<img width="1639" alt="image" src="https://user-images.githubusercontent.com/89630969/218457970-113601d3-27bb-415c-8859-e0d13e4f2b38.png">

**Comment by ashinnotfound** [comment]
场景是多人同时提问吗

**Comment by wb3368316006** [comment]
> 场景是多人同时提问吗

我一个人同时连续发了两条消息，他回复了最后一条，就报了和上图一样的错误，比之前没更新前报错还快

**Comment by ashinnotfound** [comment]
现在更新了对这类异常的处理。我测试了同时发送20条消息，都是可以正常运作的。

**Comment by wb3368316006** [comment]
> 现在更新了对这类异常的处理。我测试了同时发送20条消息，都是可以正常运作的。

嗯嗯，好嘞，我拉拉去代码尝试一下
