### ISSUE TITLE
编译问题，请教

### ISSUE THREAD

**Issue by xiaoxiaojuwuba** [ashinnotfound/ChatGPT-QQRobot#20]
![image](https://user-images.githubusercontent.com/59684982/222387820-8895f33c-da86-4ca9-aef6-d759ed74afe5.png)
请教 ，我这边把代码克隆下来之后想自己去修改，但是我克隆到本地的的代码好像找不到这些依赖，我还需要做哪些操作吗？

**Comment by ashinnotfound** [comment]
是不是maven源有问题，更新下或者换些源试试

**Comment by xiaoxiaojuwuba** [comment]
好的 等晚会我再试试

**Comment by xiaoxiaojuwuba** [comment]
谢谢了 问题已经解决 我更改为为阿里云的仓库就没问题了，顺便在下面贴一个link 
https://zhuanlan.zhihu.com/p/71998219
