### ISSUE TITLE
error

### ISSUE THREAD

**Issue by fsc07856** [ashinnotfound/ChatGPT-QQRobot#4]
net.mamoe.mirai.internal.network.components.LoginFailedExceptionAsNetworkException: Error(bot=Bot(20588006294), code=237, title=安全提醒, message=当前网络不稳定，登录失败。推荐使用常用设备或通过手机号登录。, errorInfo=)
这个怎么解决哦

**Comment by ashinnotfound** [comment]
换个网络试试？

**Comment by TochusC** [comment]
我在滑动验证时用的IP，和程序运行时的IP不同时会导致此报错产生。

解决方法：
在同一IP地址下运行程序，并进行滑动验证。

**Comment by bood4982** [comment]
这个是新增了安全验证的吗  调用api的时候返回的

Error code 1020
You do not have access to chat.openai.com.

The site owner may have set restrictions that prevent you from accessing the site.

Error details
