### ISSUE TITLE
无法使用---2023.2.8

### ISSUE THREAD

**Issue by ashinnotfound** [ashinnotfound/ChatGPT-QQRobot#7]
openai更新了chatgpt模型，目前尚不知晓模型名称，所以现在无法使用😢（HTTP 404）

**Comment by flyfhj** [comment]
qq和密码没问题，但是启动服务时显示以下错误：
net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(xxxxxx), code=235, title=温馨提示, message=当前QQ版本过低，请升级至最新版本后再登录，和本地安装的qq版本没啥关系吧？

**Comment by ashinnotfound** [comment]
> qq和密码没问题，但是启动服务时显示以下错误： net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(xxxxxx), code=235, title=温馨提示, message=当前QQ版本过低，请升级至最新版本后再登录，和本地安装的qq版本没啥关系吧？

是的，和本地的qq没关系，大概率是qq的风控导致的（腾讯认为你的账号有风险），尝试提高下qq的安全系数，比如绑定下手机号之类的

**Comment by flyfhj** [comment]
> > qq和密码没问题，但是启动服务时显示以下错误： net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(xxxxxx), code=235, title=温馨提示, message=当前QQ版本过低，请升级至最新版本后再登录，和本地安装的qq版本没啥关系吧？
> 
> 是的，和本地的qq没关系，大概率是qq的风控导致的（腾讯认为你的账号有风险），尝试提高下qq的安全系数，比如绑定下手机号之类的

好的，我试一下！

**Comment by ashinnotfound** [comment]
现在不报404了，但是会报HTTP 503服务器过载，只能接着等恢复正常🤪
