### ISSUE TITLE
可以增加支持多个 API key的功能吗

### ISSUE THREAD

**Issue by wb3368316006** [ashinnotfound/ChatGPT-QQRobot#9]
实际接入到群里边，发现如果同时五六个人提问，就会抛出503错误，有时候报很奇怪的异常，但是这次更新已经拦截异常了，目前还在跟进问题中，最后感谢大佬的项目🙏

**Comment by ashinnotfound** [comment]
理论上是可以的，我晚点写一下

**Comment by ashinnotfound** [comment]
同时提问太多应该是会报500错误，503大概是这个原因 #10 ，我现在看看怎么支持多个api key

**Comment by wb3368316006** [comment]
> 同时提问太多应该是会报500错误，503大概是这个原因 #10 ，我现在看看怎么支持多个api key

好的，谢谢解答，关于支持多个API key，hub上有一个项目时是支持的，地址https://github.com/RockChinQ/QChatGPT，这个是python写的一个，大佬参考一下，我还没看懂人家这个原理😂

**Comment by ashinnotfound** [comment]
已支持

**Comment by wb3368316006** [comment]
> 已支持

👍
